# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ispectro_xml.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1762, 877)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 0, 1726, 821))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.connect_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.connect_pushButton.setEnabled(True)
        self.connect_pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.connect_pushButton.setObjectName("connect_pushButton")
        self.gridLayout.addWidget(self.connect_pushButton, 1, 0, 1, 1)
        self.start_QPushButton = QtWidgets.QPushButton(self.groupBox)
        self.start_QPushButton.setEnabled(False)
        self.start_QPushButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.start_QPushButton.setFont(font)
        self.start_QPushButton.setStyleSheet("QPushButton { color: rgb(31, 206, 39)}")
        self.start_QPushButton.setObjectName("start_QPushButton")
        self.gridLayout.addWidget(self.start_QPushButton, 0, 0, 1, 1)
        self.stop_QPushButton = QtWidgets.QPushButton(self.groupBox)
        self.stop_QPushButton.setEnabled(False)
        self.stop_QPushButton.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stop_QPushButton.setFont(font)
        self.stop_QPushButton.setStyleSheet("QPushButton{color: red}")
        self.stop_QPushButton.setObjectName("stop_QPushButton")
        self.gridLayout.addWidget(self.stop_QPushButton, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setCheckable(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(184, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.start_freq_spinBox = QtWidgets.QSpinBox(self.tab)
        self.start_freq_spinBox.setMinimum(1)
        self.start_freq_spinBox.setMaximum(499)
        self.start_freq_spinBox.setObjectName("start_freq_spinBox")
        self.gridLayout_5.addWidget(self.start_freq_spinBox, 0, 1, 1, 1)
        self.end_freq_spinBox = QtWidgets.QSpinBox(self.tab)
        self.end_freq_spinBox.setPrefix("")
        self.end_freq_spinBox.setMinimum(1)
        self.end_freq_spinBox.setMaximum(500)
        self.end_freq_spinBox.setProperty("value", 300)
        self.end_freq_spinBox.setObjectName("end_freq_spinBox")
        self.gridLayout_5.addWidget(self.end_freq_spinBox, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 2, 0, 1, 1)
        self.step_size_spinBox = QtWidgets.QSpinBox(self.tab)
        self.step_size_spinBox.setMaximum(5)
        self.step_size_spinBox.setProperty("value", 1)
        self.step_size_spinBox.setObjectName("step_size_spinBox")
        self.gridLayout_5.addWidget(self.step_size_spinBox, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.settling_time_spinBox = QtWidgets.QSpinBox(self.tab)
        self.settling_time_spinBox.setMinimum(100)
        self.settling_time_spinBox.setMaximum(9999)
        self.settling_time_spinBox.setProperty("value", 333)
        self.settling_time_spinBox.setObjectName("settling_time_spinBox")
        self.gridLayout_5.addWidget(self.settling_time_spinBox, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.number_of_steps_spinBox_4 = QtWidgets.QSpinBox(self.tab)
        self.number_of_steps_spinBox_4.setMinimum(1)
        self.number_of_steps_spinBox_4.setMaximum(511)
        self.number_of_steps_spinBox_4.setProperty("value", 100)
        self.number_of_steps_spinBox_4.setObjectName("number_of_steps_spinBox_4")
        self.gridLayout_5.addWidget(self.number_of_steps_spinBox_4, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 0, 0, 1, 1)
        self.subject_id_lineEdit = QtWidgets.QLineEdit(self.tab)
        self.subject_id_lineEdit.setInputMask("")
        self.subject_id_lineEdit.setObjectName("subject_id_lineEdit")
        self.gridLayout_10.addWidget(self.subject_id_lineEdit, 0, 1, 1, 1)
        self.electode_dist_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab)
        self.electode_dist_doubleSpinBox.setObjectName("electode_dist_doubleSpinBox")
        self.gridLayout_10.addWidget(self.electode_dist_doubleSpinBox, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_10, 3, 1, 1, 1)
        self.apply_settings_QPushButton = QtWidgets.QPushButton(self.tab)
        self.apply_settings_QPushButton.setEnabled(False)
        self.apply_settings_QPushButton.setObjectName("apply_settings_QPushButton")
        self.gridLayout_6.addWidget(self.apply_settings_QPushButton, 0, 1, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 3, 0, 1, 1)
        self.flyby_resistor_comboBox = QtWidgets.QComboBox(self.tab)
        self.flyby_resistor_comboBox.setObjectName("flyby_resistor_comboBox")
        self.flyby_resistor_comboBox.addItem("")
        self.flyby_resistor_comboBox.addItem("")
        self.flyby_resistor_comboBox.addItem("")
        self.flyby_resistor_comboBox.addItem("")
        self.flyby_resistor_comboBox.addItem("")
        self.flyby_resistor_comboBox.addItem("")
        self.flyby_resistor_comboBox.addItem("")
        self.flyby_resistor_comboBox.addItem("")
        self.flyby_resistor_comboBox.addItem("")
        self.gridLayout_9.addWidget(self.flyby_resistor_comboBox, 2, 1, 1, 1)
        self.sweep_count_spinBox = QtWidgets.QSpinBox(self.tab)
        self.sweep_count_spinBox.setProperty("value", 1)
        self.sweep_count_spinBox.setObjectName("sweep_count_spinBox")
        self.gridLayout_9.addWidget(self.sweep_count_spinBox, 0, 1, 1, 1)
        self.flyby_calibration_comboBox = QtWidgets.QComboBox(self.tab)
        self.flyby_calibration_comboBox.setObjectName("flyby_calibration_comboBox")
        self.flyby_calibration_comboBox.addItem("")
        self.flyby_calibration_comboBox.addItem("")
        self.flyby_calibration_comboBox.addItem("")
        self.gridLayout_9.addWidget(self.flyby_calibration_comboBox, 1, 1, 1, 1)
        self.fbr_comboBox = QtWidgets.QComboBox(self.tab)
        self.fbr_comboBox.setObjectName("fbr_comboBox")
        self.fbr_comboBox.addItem("")
        self.fbr_comboBox.addItem("")
        self.fbr_comboBox.addItem("")
        self.fbr_comboBox.addItem("")
        self.fbr_comboBox.addItem("")
        self.fbr_comboBox.addItem("")
        self.fbr_comboBox.addItem("")
        self.fbr_comboBox.addItem("")
        self.fbr_comboBox.addItem("")
        self.gridLayout_9.addWidget(self.fbr_comboBox, 4, 1, 1, 1)
        self.gain_resistor_comboBox = QtWidgets.QComboBox(self.tab)
        self.gain_resistor_comboBox.setObjectName("gain_resistor_comboBox")
        self.gain_resistor_comboBox.addItem("")
        self.gain_resistor_comboBox.addItem("")
        self.gain_resistor_comboBox.addItem("")
        self.gain_resistor_comboBox.addItem("")
        self.gain_resistor_comboBox.addItem("")
        self.gain_resistor_comboBox.addItem("")
        self.gain_resistor_comboBox.addItem("")
        self.gain_resistor_comboBox.addItem("")
        self.gain_resistor_comboBox.addItem("")
        self.gridLayout_9.addWidget(self.gain_resistor_comboBox, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 2, 0, 1, 1)
        self.pga_comboBox = QtWidgets.QComboBox(self.tab)
        self.pga_comboBox.setObjectName("pga_comboBox")
        self.pga_comboBox.addItem("")
        self.pga_comboBox.addItem("")
        self.gridLayout_9.addWidget(self.pga_comboBox, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_9, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 7, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 5, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 6, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 3, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_7.addWidget(self.label_26, 4, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_7.addWidget(self.label_27, 5, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_7.addWidget(self.label_28, 6, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_7.addWidget(self.label_29, 7, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.run_regression_QPushButton = QtWidgets.QPushButton(self.tab_2)
        self.run_regression_QPushButton.setObjectName("run_regression_QPushButton")
        self.gridLayout_8.addWidget(self.run_regression_QPushButton, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 301, 481))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tableView = QtWidgets.QTableView(self.groupBox_2)
        self.tableView.setObjectName("tableView")
        self.gridLayout_11.addWidget(self.tableView, 3, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.gridLayout_11.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox_2)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.gridLayout_11.addWidget(self.treeWidget, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout_11.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.input_plot = PlotWidget(self.layoutWidget)
        self.input_plot.setObjectName("input_plot")
        self.horizontalLayout_4.addWidget(self.input_plot)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.plot1_graphicsView = PlotWidget(self.layoutWidget)
        self.plot1_graphicsView.setMinimumSize(QtCore.QSize(506, 400))
        self.plot1_graphicsView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plot1_graphicsView.setToolTipDuration(-2)
        self.plot1_graphicsView.setObjectName("plot1_graphicsView")
        self.horizontalLayout_3.addWidget(self.plot1_graphicsView)
        self.plot2_graphicsView = PlotWidget(self.layoutWidget)
        self.plot2_graphicsView.setMinimumSize(QtCore.QSize(500, 400))
        self.plot2_graphicsView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plot2_graphicsView.setObjectName("plot2_graphicsView")
        self.horizontalLayout_3.addWidget(self.plot2_graphicsView)
        self.raw_plot = PlotWidget(self.layoutWidget)
        self.raw_plot.setMinimumSize(QtCore.QSize(500, 400))
        self.raw_plot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.raw_plot.setObjectName("raw_plot")
        self.horizontalLayout_3.addWidget(self.raw_plot)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.temp_graphicsView = PlotWidget(self.layoutWidget)
        self.temp_graphicsView.setMinimumSize(QtCore.QSize(0, 70))
        self.temp_graphicsView.setMaximumSize(QtCore.QSize(16777215, 80))
        self.temp_graphicsView.setToolTip("")
        self.temp_graphicsView.setObjectName("temp_graphicsView")
        self.verticalLayout_3.addWidget(self.temp_graphicsView)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bottom_textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)
        self.bottom_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bottom_textBrowser.setObjectName("bottom_textBrowser")
        self.horizontalLayout_6.addWidget(self.bottom_textBrowser)
        self.data_table = QtWidgets.QTableWidget(self.layoutWidget)
        self.data_table.setObjectName("data_table")
        self.data_table.setColumnCount(9)
        self.data_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setItem(0, 8, item)
        self.horizontalLayout_6.addWidget(self.data_table)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1762, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.flyby_calibration_comboBox.setCurrentIndex(1)
        self.gain_resistor_comboBox.setCurrentIndex(0)
        self.start_QPushButton.objectNameChanged['QString'].connect(self.bottom_textBrowser.insertPlainText)
        self.connect_pushButton.clicked.connect(self.checkBox.toggle)
        self.checkBox.toggled['bool'].connect(self.start_QPushButton.setEnabled)
        self.checkBox.toggled['bool'].connect(self.stop_QPushButton.setEnabled)
        self.connect_pushButton.released.connect(self.connect_pushButton.hide)
        self.checkBox.toggled['bool'].connect(self.apply_settings_QPushButton.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "ispectro"))
        self.centralwidget.setStatusTip(_translate("mainWindow", "Hover Over Things to See Info Here"))
        self.groupBox.setTitle(_translate("mainWindow", "Device Controls"))
        self.connect_pushButton.setText(_translate("mainWindow", "connect"))
        self.start_QPushButton.setText(_translate("mainWindow", "Start"))
        self.stop_QPushButton.setText(_translate("mainWindow", "Stop"))
        self.checkBox.setText(_translate("mainWindow", "connected"))
        self.start_freq_spinBox.setSuffix(_translate("mainWindow", " kHz"))
        self.end_freq_spinBox.setSuffix(_translate("mainWindow", " kHz"))
        self.label_9.setText(_translate("mainWindow", "Step Size:"))
        self.step_size_spinBox.setSuffix(_translate("mainWindow", " kHz"))
        self.label_11.setText(_translate("mainWindow", "Settling Time:"))
        self.label_7.setText(_translate("mainWindow", "Start Freq:"))
        self.settling_time_spinBox.setSuffix(_translate("mainWindow", " ms"))
        self.label_10.setText(_translate("mainWindow", "Number of Steps:"))
        self.label_8.setText(_translate("mainWindow", "End Freq:"))
        self.label_12.setText(_translate("mainWindow", "Subject ID:"))
        self.subject_id_lineEdit.setText(_translate("mainWindow", "no ID"))
        self.electode_dist_doubleSpinBox.setSuffix(_translate("mainWindow", " cm"))
        self.label_13.setText(_translate("mainWindow", "Electrode Dist."))
        self.apply_settings_QPushButton.setText(_translate("mainWindow", "Apply Settings"))
        self.label_3.setText(_translate("mainWindow", "Gain Resistor:"))
        self.flyby_resistor_comboBox.setItemText(0, _translate("mainWindow", "OFF"))
        self.flyby_resistor_comboBox.setItemText(1, _translate("mainWindow", "R67"))
        self.flyby_resistor_comboBox.setItemText(2, _translate("mainWindow", "R69"))
        self.flyby_resistor_comboBox.setItemText(3, _translate("mainWindow", "R71"))
        self.flyby_resistor_comboBox.setItemText(4, _translate("mainWindow", "R73"))
        self.flyby_resistor_comboBox.setItemText(5, _translate("mainWindow", "R65"))
        self.flyby_resistor_comboBox.setItemText(6, _translate("mainWindow", "R74/R72/C81"))
        self.flyby_resistor_comboBox.setItemText(7, _translate("mainWindow", "R70/R68/C79"))
        self.flyby_resistor_comboBox.setItemText(8, _translate("mainWindow", "R66/R64/C75"))
        self.flyby_calibration_comboBox.setCurrentText(_translate("mainWindow", "A"))
        self.flyby_calibration_comboBox.setItemText(0, _translate("mainWindow", "OFF"))
        self.flyby_calibration_comboBox.setItemText(1, _translate("mainWindow", "A"))
        self.flyby_calibration_comboBox.setItemText(2, _translate("mainWindow", "B"))
        self.fbr_comboBox.setItemText(0, _translate("mainWindow", "OFF"))
        self.fbr_comboBox.setItemText(1, _translate("mainWindow", "R1"))
        self.fbr_comboBox.setItemText(2, _translate("mainWindow", "R4"))
        self.fbr_comboBox.setItemText(3, _translate("mainWindow", "R6"))
        self.fbr_comboBox.setItemText(4, _translate("mainWindow", "R7"))
        self.fbr_comboBox.setItemText(5, _translate("mainWindow", "R11"))
        self.fbr_comboBox.setItemText(6, _translate("mainWindow", "R15"))
        self.fbr_comboBox.setItemText(7, _translate("mainWindow", "R17"))
        self.fbr_comboBox.setItemText(8, _translate("mainWindow", "R19"))
        self.gain_resistor_comboBox.setCurrentText(_translate("mainWindow", "OFF"))
        self.gain_resistor_comboBox.setItemText(0, _translate("mainWindow", "OFF"))
        self.gain_resistor_comboBox.setItemText(1, _translate("mainWindow", "R53"))
        self.gain_resistor_comboBox.setItemText(2, _translate("mainWindow", "R54"))
        self.gain_resistor_comboBox.setItemText(3, _translate("mainWindow", "R55"))
        self.gain_resistor_comboBox.setItemText(4, _translate("mainWindow", "R56"))
        self.gain_resistor_comboBox.setItemText(5, _translate("mainWindow", "R44"))
        self.gain_resistor_comboBox.setItemText(6, _translate("mainWindow", "R46"))
        self.gain_resistor_comboBox.setItemText(7, _translate("mainWindow", "R50"))
        self.gain_resistor_comboBox.setItemText(8, _translate("mainWindow", "R52"))
        self.label_5.setText(_translate("mainWindow", "Flyby Resistor:"))
        self.pga_comboBox.setItemText(0, _translate("mainWindow", "1x"))
        self.pga_comboBox.setItemText(1, _translate("mainWindow", "5x"))
        self.label_4.setText(_translate("mainWindow", "FBR:"))
        self.label_2.setText(_translate("mainWindow", "Flyby Calibration:"))
        self.label_6.setText(_translate("mainWindow", "PGA:"))
        self.label.setText(_translate("mainWindow", "Sweep Count:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Settings"))
        self.label_16.setText(_translate("mainWindow", "TextLabel"))
        self.label_20.setText(_translate("mainWindow", "TextLabel"))
        self.label_17.setText(_translate("mainWindow", "TextLabel"))
        self.label_19.setText(_translate("mainWindow", "TextLabel"))
        self.label_15.setText(_translate("mainWindow", "TextLabel"))
        self.label_14.setText(_translate("mainWindow", "TextLabel"))
        self.label_18.setText(_translate("mainWindow", "TextLabel"))
        self.label_21.setText(_translate("mainWindow", "TextLabel"))
        self.label_22.setText(_translate("mainWindow", "TextLabel"))
        self.label_23.setText(_translate("mainWindow", "TextLabel"))
        self.label_24.setText(_translate("mainWindow", "TextLabel"))
        self.label_25.setText(_translate("mainWindow", "TextLabel"))
        self.label_26.setText(_translate("mainWindow", "TextLabel"))
        self.label_27.setText(_translate("mainWindow", "TextLabel"))
        self.label_28.setText(_translate("mainWindow", "TextLabel"))
        self.label_29.setText(_translate("mainWindow", "TextLabel"))
        self.run_regression_QPushButton.setText(_translate("mainWindow", "Run Regression"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "Regression"))
        self.groupBox_2.setTitle(_translate("mainWindow", "All Scans"))
        self.pushButton_3.setText(_translate("mainWindow", "View"))
        self.pushButton_4.setText(_translate("mainWindow", "Delete"))
        self.pushButton_2.setText(_translate("mainWindow", "Un-Plot Data"))
        self.pushButton.setText(_translate("mainWindow", "Plot Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("mainWindow", "Page"))
        self.temp_graphicsView.setStatusTip(_translate("mainWindow", "Internal Device Temperature"))
        item = self.data_table.verticalHeaderItem(0)
        item.setText(_translate("mainWindow", "index1"))
        item = self.data_table.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "frequency"))
        item = self.data_table.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Lead R"))
        item = self.data_table.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Lead I"))
        item = self.data_table.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Cal1 R"))
        item = self.data_table.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Cal1 I"))
        item = self.data_table.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Cal2 R"))
        item = self.data_table.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "Cal2 I"))
        item = self.data_table.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "Temp C"))
        item = self.data_table.horizontalHeaderItem(8)
        item.setText(_translate("mainWindow", "Status"))
        __sortingEnabled = self.data_table.isSortingEnabled()
        self.data_table.setSortingEnabled(False)
        item = self.data_table.item(0, 0)
        item.setText(_translate("mainWindow", "f"))
        item = self.data_table.item(0, 1)
        item.setText(_translate("mainWindow", "a"))
        item = self.data_table.item(0, 2)
        item.setText(_translate("mainWindow", "b"))
        item = self.data_table.item(0, 3)
        item.setText(_translate("mainWindow", "a2"))
        item = self.data_table.item(0, 4)
        item.setText(_translate("mainWindow", "b2"))
        item = self.data_table.item(0, 5)
        item.setText(_translate("mainWindow", "c3"))
        item = self.data_table.item(0, 6)
        item.setText(_translate("mainWindow", "c3"))
        item = self.data_table.item(0, 7)
        item.setText(_translate("mainWindow", "temp"))
        item = self.data_table.item(0, 8)
        item.setText(_translate("mainWindow", "on or off"))
        self.data_table.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuEdit.setTitle(_translate("mainWindow", "Edit"))
        self.menuView.setTitle(_translate("mainWindow", "View"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))

from pyqtgraph import PlotWidget
